import { RegistryItemSchema, RegistryType } from "./types";

type ComponentType = Omit<
  RegistryItemSchema,
  "$schema" | "files" | "type" | "author"
> &
  Partial<Pick<RegistryItemSchema, "type" | "author">> & {
    path: string;
    files?: {
      path: string;
      name: string;
      content: string;
      type: RegistryType;
    }[];
  };

// Static component list - this is auto-generated by the build script
export const components: ComponentType[] = [
  {
    name: "accordion",
    title: "Accordion",
    description: "A minimalistic accordion component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/accordion",
    dependencies: [],
    files: [
      {
        path: "../app/components/accordion",
        name: "accordion",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "accordion-last",
    title: "Accordion Last",
    description: "A minimalistic accordion component with last item styling designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/accordion-last",
    dependencies: [],
    files: [
      {
        path: "../app/components/accordion-last",
        name: "accordion-last",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "amazongift",
    title: "Amazongift",
    description: "A minimalistic Amazon gift card component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/amazongift",
    dependencies: [],
    files: [
      {
        path: "../app/components/amazongift",
        name: "amazongift",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "aurora",
    title: "Aurora",
    description: "A minimalistic aurora component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/aurora",
    dependencies: [],
    files: [
      {
        path: "../app/components/aurora",
        name: "aurora",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "badge",
    title: "Badge",
    description: "A minimalistic badge component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/badge",
    dependencies: [],
    files: [
      {
        path: "../app/components/badge",
        name: "badge",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "bento-grid",
    title: "Bento Grid",
    description: "A minimalistic bento grid component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/bento-grid",
    dependencies: [],
    files: [
      {
        path: "../app/components/bento-grid",
        name: "bento-grid",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "button",
    title: "Button",
    description: "A minimalistic button component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/button",
    dependencies: [],
    files: [
      {
        path: "../app/components/button",
        name: "button",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "card",
    title: "Card",
    description: "A minimalistic card component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/card",
    dependencies: [],
    files: [
      {
        path: "../app/components/card",
        name: "card",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "carousel",
    title: "Carousel",
    description: "A minimalistic carousel component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/carousel",
    dependencies: [],
    files: [
      {
        path: "../app/components/carousel",
        name: "carousel",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "codeprofile",
    title: "Codeprofile",
    description: "A minimalistic codeprofile component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/codeprofile",
    dependencies: [],
    files: [
      {
        path: "../app/components/codeprofile",
        name: "codeprofile",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "copybutton",
    title: "Copybutton",
    description: "A minimalistic copybutton component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/copybutton",
    dependencies: [],
    files: [
      {
        path: "../app/components/copybutton",
        name: "copybutton",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "decrypting",
    title: "Decrypting",
    description: "A minimalistic decrypting component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/decrypting",
    dependencies: [],
    files: [
      {
        path: "../app/components/decrypting",
        name: "decrypting",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "divider",
    title: "Divider",
    description: "A minimalistic divider component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/divider",
    dependencies: [],
    files: [
      {
        path: "../app/components/divider",
        name: "divider",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "dock",
    title: "Dock",
    description: "A minimalistic dock component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/dock",
    dependencies: [],
    files: [
      {
        path: "../app/components/dock",
        name: "dock",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "doctabs",
    title: "Doctabs",
    description: "A minimalistic doctabs component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/doctabs",
    dependencies: [],
    files: [
      {
        path: "../app/components/doctabs",
        name: "doctabs",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "A minimalistic drawer component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/drawer",
    dependencies: [],
    files: [
      {
        path: "../app/components/drawer",
        name: "drawer",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "dropdown",
    title: "Dropdown",
    description: "A minimalistic dropdown component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/dropdown",
    dependencies: [],
    files: [
      {
        path: "../app/components/dropdown",
        name: "dropdown",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "falling-glitch",
    title: "Falling Glitch",
    description: "A minimalistic falling glitch component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/falling-glitch",
    dependencies: [],
    files: [
      {
        path: "../app/components/falling-glitch",
        name: "falling-glitch",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "filetree",
    title: "Filetree",
    description: "A minimalistic filetree component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/filetree",
    dependencies: [],
    files: [
      {
        path: "../app/components/filetree",
        name: "filetree",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "flipwords",
    title: "Flipwords",
    description: "A minimalistic flip words animation component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/flipwords",
    dependencies: [],
    files: [
      {
        path: "../app/components/flipwords",
        name: "flipwords",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "forgotpassword",
    title: "Forgotpassword",
    description: "A minimalistic forgotpassword component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/forgotpassword",
    dependencies: [],
    files: [
      {
        path: "../app/components/forgotpassword",
        name: "forgotpassword",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "fuzzy",
    title: "Fuzzy",
    description: "A minimalistic fuzzy search component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/fuzzy",
    dependencies: [],
    files: [
      {
        path: "../app/components/fuzzy",
        name: "fuzzy",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "gradient",
    title: "Gradient",
    description: "A minimalistic gradient component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/gradient",
    dependencies: [],
    files: [
      {
        path: "../app/components/gradient",
        name: "gradient",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "gradient-accordion",
    title: "Gradient Accordion",
    description: "A minimalistic gradient accordion component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/gradient-accordion",
    dependencies: [],
    files: [
      {
        path: "../app/components/gradient-accordion",
        name: "gradient-accordion",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "gradientgen",
    title: "Gradientgen",
    description: "A minimalistic gradientgen component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/gradientgen",
    dependencies: [],
    files: [
      {
        path: "../app/components/gradientgen",
        name: "gradientgen",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "hero",
    title: "Hero",
    description: "A minimalistic hero component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/hero",
    dependencies: [],
    files: [
      {
        path: "../app/components/hero",
        name: "hero",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "imageswiper",
    title: "Imageswiper",
    description: "A minimalistic imageswiper component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/imageswiper",
    dependencies: [],
    files: [
      {
        path: "../app/components/imageswiper",
        name: "imageswiper",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "integrations",
    title: "Integrations",
    description: "A minimalistic integrations component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/integrations",
    dependencies: [],
    files: [
      {
        path: "../app/components/integrations",
        name: "integrations",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "loaders",
    title: "Loaders",
    description: "A minimalistic loaders component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/loaders",
    dependencies: [],
    files: [
      {
        path: "../app/components/loaders",
        name: "loaders",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "login",
    title: "Login",
    description: "A minimalistic login component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/login",
    dependencies: [],
    files: [
      {
        path: "../app/components/login",
        name: "login",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "magic",
    title: "Magic",
    description: "A minimalistic magic component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/magic",
    dependencies: [],
    files: [
      {
        path: "../app/components/magic",
        name: "magic",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "masonary",
    title: "Masonary",
    description: "A minimalistic masonary component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/masonary",
    dependencies: [],
    files: [
      {
        path: "../app/components/masonary",
        name: "masonary",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "moving-grid",
    title: "Moving Grid",
    description: "A minimalistic moving grid component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/moving-grid",
    dependencies: [],
    files: [
      {
        path: "../app/components/moving-grid",
        name: "moving-grid",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "multiselector",
    title: "Multiselector",
    description: "A minimalistic multiselector component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/multiselector",
    dependencies: [],
    files: [
      {
        path: "../app/components/multiselector",
        name: "multiselector",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "navbar",
    title: "Navbar",
    description: "A minimalistic navbar component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/navbar",
    dependencies: [],
    files: [
      {
        path: "../app/components/navbar",
        name: "navbar",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "network",
    title: "Network",
    description: "A minimalistic network component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/network",
    dependencies: [],
    files: [
      {
        path: "../app/components/network",
        name: "network",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "noise",
    title: "Noise",
    description: "A minimalistic noise component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/noise",
    dependencies: [],
    files: [
      {
        path: "../app/components/noise",
        name: "noise",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "password",
    title: "Password",
    description: "A minimalistic password input component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/password",
    dependencies: [],
    files: [
      {
        path: "../app/components/password",
        name: "password",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "pattern",
    title: "Pattern",
    description: "A collection of beautiful background patterns designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/pattern",
    dependencies: [],
    files: [
      {
        path: "../app/components/pattern",
        name: "pattern",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "portfolio",
    title: "Portfolio",
    description: "A minimalistic portfolio component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/portfolio",
    dependencies: [],
    files: [
      {
        path: "../app/components/portfolio",
        name: "portfolio",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "pricing",
    title: "Pricing",
    description: "A minimalistic pricing component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/pricing",
    dependencies: [],
    files: [
      {
        path: "../app/components/pricing",
        name: "pricing",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "prompt",
    title: "Prompt",
    description: "A minimalistic prompt component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/prompt",
    dependencies: [],
    files: [
      {
        path: "../app/components/prompt",
        name: "prompt",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "resize-handle",
    title: "Resize Handle",
    description: "A minimalistic resize handle component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/resize-handle",
    dependencies: [],
    files: [
      {
        path: "../app/components/resize-handle",
        name: "resize-handle",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "search",
    title: "Search",
    description: "A minimalistic search component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/search",
    dependencies: [],
    files: [
      {
        path: "../app/components/search",
        name: "search",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "shimmer",
    title: "Shimmer",
    description: "A minimalistic shimmer component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/shimmer",
    dependencies: [],
    files: [
      {
        path: "../app/components/shimmer",
        name: "shimmer",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "signin",
    title: "Signin",
    description: "A minimalistic signin component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/signin",
    dependencies: [],
    files: [
      {
        path: "../app/components/signin",
        name: "signin",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "spotlightcard",
    title: "Spotlightcard",
    description: "A minimalistic spotlightcard component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/spotlightcard",
    dependencies: [],
    files: [
      {
        path: "../app/components/spotlightcard",
        name: "spotlightcard",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "svg-icons",
    title: "Svg Icons",
    description: "A minimalistic svg icons component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/svg-icons",
    dependencies: [],
    files: [
      {
        path: "../app/components/svg-icons",
        name: "svg-icons",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "A minimalistic tab component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/tabs",
    dependencies: [],
    files: [
      {
        path: "../app/components/tabs",
        name: "tabs",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "tabs-classic",
    title: "Tabs Classic",
    description: "A minimalistic tabs classic component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/tabs-classic",
    dependencies: [],
    files: [
      {
        path: "../app/components/tabs-classic",
        name: "tabs-classic",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "tabs-fancy",
    title: "Tabs Fancy",
    description: "A minimalistic tabs fancy component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/tabs-fancy",
    dependencies: [],
    files: [
      {
        path: "../app/components/tabs-fancy",
        name: "tabs-fancy",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "testimonial",
    title: "Testimonial",
    description: "A minimalistic testimonial component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/testimonial",
    dependencies: [],
    files: [
      {
        path: "../app/components/testimonial",
        name: "testimonial",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "text",
    title: "Text",
    description: "A minimalistic text component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/text",
    dependencies: [],
    files: [
      {
        path: "../app/components/text",
        name: "text",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "textreveal",
    title: "Textreveal",
    description: "A minimalistic textreveal component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/textreveal",
    dependencies: [],
    files: [
      {
        path: "../app/components/textreveal",
        name: "textreveal",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "ticker",
    title: "Ticker",
    description: "A minimalistic ticker component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/ticker",
    dependencies: [],
    files: [
      {
        path: "../app/components/ticker",
        name: "ticker",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "toast",
    title: "Toast",
    description: "A minimalistic toast component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/toast",
    dependencies: [],
    files: [
      {
        path: "../app/components/toast",
        name: "toast",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "transactions",
    title: "Transactions",
    description: "A minimalistic transactions component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/transactions",
    dependencies: [],
    files: [
      {
        path: "../app/components/transactions",
        name: "transactions",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "twostep",
    title: "Twostep",
    description: "A minimalistic two-step verification component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/twostep",
    dependencies: [],
    files: [
      {
        path: "../app/components/twostep",
        name: "twostep",
        content: "",
        type: "registry:component",
      },
    ],
  },
  {
    name: "waitlist",
    title: "Waitlist",
    description: "A minimalistic waitlist component designed with React and Tailwind CSS.",
    type: "registry:component",
    path: "../app/components/waitlist",
    dependencies: [],
    files: [
      {
        path: "../app/components/waitlist",
        name: "waitlist",
        content: "",
        type: "registry:component",
      },
    ],
  }
];
