import { RegistryItemSchema, RegistryType } from "./types";

type TemplateType = Omit<
  RegistryItemSchema,
  "$schema" | "files" | "type" | "author"
> &
  Partial<Pick<RegistryItemSchema, "type" | "author">> & {
    path: string;
    files?: {
      path: string;
      name: string;
      content: string;
      type: RegistryType;
    }[];
  };

// Static template list - this is auto-generated by the build script
export const templates: TemplateType[] = [
  {
    name: "bridge",
    title: "Bridge",
    description: "A minimalistic bridge template designed with React and Tailwind CSS.",
    type: "registry:template",
    path: "../app/templates/bridge",
    dependencies: [],
  },
  {
    name: "defi-dashboard",
    title: "Defi Dashboard",
    description: "A minimalistic defi dashboard template designed with React and Tailwind CSS.",
    type: "registry:template",
    path: "../app/templates/defi-dashboard",
    dependencies: [],
  },
  {
    name: "nft-market",
    title: "Nft Market",
    description: "A minimalistic nft market template designed with React and Tailwind CSS.",
    type: "registry:template",
    path: "../app/templates/nft-market",
    dependencies: [],
  },
  {
    name: "stake",
    title: "Stake",
    description: "A minimalistic stake template designed with React and Tailwind CSS.",
    type: "registry:template",
    path: "../app/templates/stake",
    dependencies: [],
  }
];
